name: My Farm API Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Stop existing container
        run: |
          sudo docker stop my-farm || true
          sudo docker rm my-farm || true

      - name: Remove old image
        run: |
          sudo docker image rm my-farm:latest || true

      - name: Build Docker image
        run: |
          sudo docker build \
            -t my-farm:latest \
            .

      - name: Build and deploy
        run: |
          sudo docker compose down
          sudo docker compose build
          sudo docker compose up -d

